### ISSUE TITLE
Unable to use -e option along with --name/--class option

### ISSUE THREAD

**Issue by zaytsev** [caleb-/evilvte#14]
Hi! It seems gtk_init modifies content of argv when it detects --name/--class arguments and default_argv looses "-e" option parameters.
The following code (I'm not a C-expert, sorry) fixes this problem:

``` c
int gtk_argc = argc;
char **gtk_argv = (char**)malloc(argc * sizeof(char*));
int ii = 0;
for (ii = 0; ii < argc; ii++)
    gtk_argv[ii] = argv[ii];

  gtk_init(&gtk_argc, &gtk_argv);

free(gtk_argv);
```

**Comment by caleb-** [comment]
@zaytsev 
Thank you! I will test and merge this. :-)
