### ISSUE TITLE
Shift-arrow keybinding

### ISSUE THREAD

**Issue by istitov** [caleb-/evilvte#2]
That would be very useful to make possible assign shift+arrow keybinding via config file (e.g. for selection of the next or previous tab)

**Comment by caleb-** [comment]
Thanks.
Hotkey support of evilvte do need a totally rewrite.
I think I will at least provide a workaround for shift-arrow in next tarball.

Feel free to request other useful keybindings or features. :-)

**Comment by istitov** [comment]
I'll do, I promise :-)

**Comment by efphe** [comment]
it would be nice,

I have the same need: binding next/prev tab to Shift+Left/Right

**Comment by shenfeng** [comment]
on Linux, chrome, firefox trend to use `ALT+number` to switch to the given tab.

evilvte has no support for ALT keybinding ( am I right ?), 
I patched it myself:  https://github.com/shenfeng/evilvte/commit/f20add2cade30b282d0871d1dae20d99277a20b9#diff-2

Do you have any plan  to add it.

**Comment by caleb-** [comment]
@shenfeng
Thanks, I will provide a workaround for it. :-)

**Comment by caleb-** [comment]
Fixed in commit ba42d2a.

**Comment by istitov** [comment]
Finally! Thank you so much!
