### ISSUE TITLE
Fading of inactive windows

### ISSUE THREAD

**Issue by lxcode** [caleb-/evilvte#24]
One very nice thing about urxvt is that it allows to fade the text of inactive terminals by a certain amount, making it very visually obvious which window is active. This is especially useful with minimal window managers like dwm, where visual cues are fairly few. Any chance of this getting implemented?

**Comment by caleb-** [comment]
Sorry I am too busy and did not login to github for several weeks.
I have put it to my TODO list, thank you. :-)
