### ISSUE TITLE
Tag your project

### ISSUE THREAD

**Issue by cicku** [caleb-/evilvte#28]
Hi,

I'm going to package it into Fedora, but I hope you can add a proper tag for each release on github.

Thanks.

**Comment by caleb-** [comment]
git tag has some limits so I do not plan to use it.
Anyway, I do not think Fedora only make rpms for upstreams with git tag.

**Comment by cicku** [comment]
Fedora packagers can do anything they want, but we'd like to know its major version as well, otherwise your software will be shown with version 0.

We make RPM because we think it's stable, not a VCS snapshot version.

What about release function?
