### ISSUE TITLE
default directory when launched via HOTKEY_OPEN_NEW_WINDOW

### ISSUE THREAD

**Issue by pnrao** [caleb-/evilvte#3]
Config:
# define DEFAULT_DIRECTORY      g_get_current_dir()
# define HOTKEY_OPEN_NEW_WINDOW       CTRL GDK_N

Steps to reproduce:
visit /usr/share/misc and start evilvte from that folder (entering the command on a terminal or via file manager). Evilvte starts with /usr/share/misc as the initial directory.
Do "cd ../awk" and hit Ctrl-Shift-N to open a new terminal.

Expected behaviour:
The new shell opens in /usr/share/awk

Observed behaviour:
The new shell opens in /usr/share/misc

**Comment by caleb-** [comment]
Thanks.
I will try a workaround before next tarball release. (Usually I release a tarball per month.)
