### ISSUE TITLE
Update to vte 2.91 API

### ISSUE THREAD

**Issue by dffischer** [caleb-/evilvte#35]
In vte version 0.38 the API was changed to version 2.91, changing or removing some of the functions used by evilvte, causing compilation or execution to fail after upgrade.

**Comment by caleb-** [comment]
Sorry I have not login to github for several months.
I have no plan to support VTE API 2.91.
I still use evilvte everyday but keep GTK+ 3.x away. :-P

**Comment by dffischer** [comment]
Thanks for the clear statement.

As I found found evilvte in search of a gnome-terminal replacement supporting transparency and it served me very well until the API upgrade, anyone with similar need may perhaps be hinted to [this patch found in Fedora](http://pkgs.fedoraproject.org/cgit/gnome-terminal.git/plain/0001-Restore-transparency-gnome-3-14.patch).
