### ISSUE TITLE
scroll screen up/down

### ISSUE THREAD

**Issue by shenfeng** [caleb-/evilvte#4]
This is a feature request.

Emacs has `Ctrl+v` `Alt-v`
Vim has `Ctrl+f` `Ctrl+b`

to scroll up/down one screen.

``` c
      GET_CURRENT_TAB(gtk_notebook_get_current_page(GTK_NOTEBOOK(notebook)));
      gtk_test_widget_click(term->vte, 4, 0);
```

only scroll about 7 lines.

How to scroll faster in evilvte?

**Comment by caleb-** [comment]
I would suggest Shift+PgUp / Shift+PgDn to scroll one screen.

HOTKEYˍMIMICˍSCROLLˍ\* in evilvte do really mimic mouse scroll, so it depends on how you configure your mouse.
For me it only scroll 3 lines. :-)

**Comment by caleb-** [comment]
I will search how to scroll one screen in VTE.
It is good to define user's personal hotkeys to  scroll one screen.
