### ISSUE TITLE
Caps lock changes hot key behavior

### ISSUE THREAD

**Issue by xaocon** [caleb-/evilvte#7]
For example if you have:
# define HOTKEY_COPY                  CTRL(GDK_C)

in your config.h then `<ctrl> + <shift> + c` works. However if you turn on the caps lock it changes to just `<ctrl> + c`.

**Comment by caleb-** [comment]
Thanks!
I will try workaround / solution for this. :-)

**Comment by caleb-** [comment]
@xaocon 
Not everything fixed, but the problem with ＜ctrl＞ + ＜shift＞ has been reduced to minimum by now. :-)

**Comment by xaocon** [comment]
thanks!
